In [1]:
import pandas as pd

data = pd.read_csv('test.csv')

In [2]:
data[data['hold_time'] > '2016-03-31' ]

,﻿star_trail_info_id,star_name,create_date,hold_time,count
823,3741,陈奕迅,2015-08-20 12:22:19,2016-10-22 19:00:00,1
2524,6302,初音未来,2015-10-06 14:16:14,2016-03-31 00:00:00,1
2525,6303,初音未来,2015-10-06 14:16:14,2016-04-05 00:00:00,1
2526,6304,初音未来,2015-10-06 14:16:14,2016-04-09 00:00:00,1
2527,6305,初音未来,2015-10-06 14:16:14,2016-04-10 00:00:00,1
2746,6593,SHINee,2015-10-08 11:52:36,2016-04-02 00:00:00,1
2747,6594,SHINee,2015-10-08 11:52:36,2016-04-05 00:00:00,1
2748,6595,SHINee,2015-10-08 11:52:36,2016-04-06 00:00:00,1
2749,6596,SHINee,2015-10-08 11:52:36,2016-04-09 00:00:00,1
2750,6597,SHINee,2015-10-08 11:52:36,2016-04-10 00:00:00,1
2751,6598,SHINee,2015-10-08 11:52:36,2016-04-23 00:00:00,1
2752,6599,SHINee,2015-10-08 11:52:36,2016-04-24 00:00:00,1
3219,7408,陈奕迅,2015-10-21 00:25:43,2016-05-07 00:00:00,1
3542,7875,伍佰,2015-10-28 16:31:12,2016-04-15 00:00:00,1
3543,7876,伍佰,2015-10-28 16:31:12,2016-04-16 00:00:00,1
3607,7988,蔡依林,2015-10-30 15:18:59,2016-04-23 00:00:00,1
3630,8014,罗志祥,2015-10-30 15:20:22,2016-05-28 00:00:00,1
3671,8104,林宥嘉,2015-11-02 22:18:45,2016-06-25 19:30:00,1
3675,8113,张敬轩,2015-11-02 22:18:45,2016-04-09 00:00:00,1
3676,8119,蔡依林,2015-11-02 22:18:45,2016-04-16 00:00:00,1
3786,8322,Adam Lambert,2015-11-04 13:31:22,2016-04-13 00:00:00,1
3787,8323,Adam Lambert,2015-11-04 13:31:22,2016-04-14 00:00:00,1
3788,8324,Adam Lambert,2015-11-04 13:31:22,2016-04-16 00:00:00,1
3789,8325,Adam Lambert,2015-11-04 13:31:22,2016-04-18 00:00:00,1
3790,8326,Adam Lambert,2015-11-04 13:31:22,2016-04-23 00:00:00,1
3791,8327,Adam Lambert,2015-11-04 13:31:22,2016-04-24 00:00:00,1
3792,8328,Adam Lambert,2015-11-04 13:31:22,2016-04-25 00:00:00,1
3793,8329,Adam Lambert,2015-11-04 13:31:22,2016-04-30 00:00:00,1
3794,8330,Adam Lambert,2015-11-04 13:31:22,2016-05-02 00:00:00,1
3795,8331,Adam Lambert,2015-11-04 13:31:22,2016-05-04 00:00:00,1
...,...,...,...,...,...
13290,21304,生田斗真,2016-04-11 17:42:10,2016-10-08 13:00:00,1
13291,21305,生田斗真,2016-04-11 17:42:10,2016-10-09 13:00:00,1
13292,21306,生田斗真,2016-04-11 17:42:10,2016-10-19 18:30:00,1
13293,21307,生田斗真,2016-04-11 17:42:10,2016-10-21 18:30:00,1
13294,21308,生田斗真,2016-04-11 17:42:10,2016-10-22 13:00:00,1
13295,21309,生田斗真,2016-04-11 17:42:10,2016-10-23 13:00:00,1
13296,21310,生田斗真,2016-04-11 17:42:10,2016-10-24 13:00:00,1
13297,21311,生田斗真,2016-04-11 17:42:10,2016-10-25 13:00:00,1
13298,21312,生田斗真,2016-04-11 17:42:10,2016-10-26 13:00:00,1
13299,21313,生田斗真,2016-04-11 17:42:10,2016-10-28 18:30:00,1
13300,21314,生田斗真,2016-04-11 17:42:10,2016-10-29 13:00:00,1
13301,21315,生田斗真,2016-04-11 17:42:10,2016-10-30 13:00:00,1
13302,21316,生田斗真,2016-04-11 17:42:10,2016-10-31 13:00:00,1
13303,21320,Jessica郑秀妍,2016-04-11 17:42:10,2016-04-11 00:00:00,1
13304,21321,曹轩宾,2016-04-11 17:42:10,2016-04-23 20:00:00,1
13305,21323,李圣经,2016-04-11 17:42:10,2016-04-20 00:00:00,1
13306,21326,郭冬临,2016-04-11 17:42:10,2016-04-24 00:00:00,1
13307,21327,张宇,2016-04-11 17:42:10,2016-05-21 19:30:00,1
13308,21330,余心恬,2016-04-11 17:42:10,2016-04-17 16:00:00,1
13309,21331,郑恺,2016-04-11 17:42:10,2016-04-17 00:00:00,1
13310,21332,朴宝剑,2016-04-11 17:50:05,2016-04-11 00:00:00,1
13311,21333,朴宝剑,2016-04-11 17:50:05,2016-04-12 00:00:00,1
13312,21334,朴宝剑,2016-04-11 17:50:05,2016-04-14 00:00:00,1
13313,21335,宋仲基,2016-04-11 17:50:05,2016-04-11 00:00:00,1
13314,21336,宋仲基,2016-04-11 17:50:05,2016-04-12 00:00:00,1
13315,21337,宋仲基,2016-04-11 17:50:05,2016-04-13 00:00:00,1
13316,21338,宋仲基,2016-04-11 17:50:05,2016-04-14 00:00:00,1
13317,21339,宋仲基,2016-04-11 17:50:05,2016-04-15 00:00:00,1
13318,21340,宋仲基,2016-04-11 17:50:05,2016-04-16 00:00:00,1
13319,21343,唐嫣,2016-04-12 09:51:42,2016-04-12 00:00:00,1

In [3]:
star_name = data['star_name'].unique()

In [4]:
len(star_name)

1549

In [5]:
print(star_name)

['张玮' '盛骏' '丁当' ..., 'I.O.I' '易嘉爱' '生田斗真']

In [6]:
import numpy as np
result = pd.DataFrame(star_name)
result.to_csv('star_name.csv')

In [7]:
data[data['star_name'] == '宋仲基']

,﻿star_trail_info_id,star_name,create_date,hold_time,count
9726,16477,宋仲基,2016-02-18 10:04:18,2016-02-20 00:00:00,1
11067,18231,宋仲基,2016-03-08 12:09:38,2016-03-08 00:00:00,1
11467,18755,宋仲基,2016-03-14 17:25:38,2016-03-18 00:00:00,1
11468,18756,宋仲基,2016-03-14 17:26:15,2016-03-17 00:00:00,1
11522,18824,宋仲基,2016-03-15 12:16:37,2016-05-27 00:00:00,1
11931,19355,宋仲基,2016-03-21 11:42:11,2016-05-14 00:00:00,1
11932,19356,宋仲基,2016-03-21 11:42:11,2016-05-21 00:00:00,1
11933,19357,宋仲基,2016-03-21 11:42:11,2016-05-28 00:00:00,1
11934,19358,宋仲基,2016-03-21 11:42:11,2016-06-05 00:00:00,1
11935,19359,宋仲基,2016-03-21 11:42:11,2016-06-11 00:00:00,1
11989,19441,宋仲基,2016-03-21 16:17:12,2016-03-25 00:00:00,1
12233,19791,宋仲基,2016-03-24 11:18:50,2016-06-17 00:00:00,1
12234,19792,宋仲基,2016-03-24 11:18:50,2016-06-24 00:00:00,1
12285,19861,宋仲基,2016-03-25 10:02:13,2016-04-17 14:00:00,1
12443,20073,宋仲基,2016-03-28 15:02:53,2016-03-29 00:00:00,1
12444,20074,宋仲基,2016-03-28 15:02:53,2016-04-02 00:00:00,1
12474,20123,宋仲基,2016-03-29 09:52:51,2016-05-07 18:00:00,1
12482,20134,宋仲基,2016-03-29 10:39:31,2016-03-30 00:00:00,1
12987,20812,宋仲基,2016-04-05 11:53:16,2016-04-06 00:00:00,1
12988,20813,宋仲基,2016-04-05 11:53:16,2016-04-07 00:00:00,1
12989,20814,宋仲基,2016-04-05 11:53:16,2016-04-08 00:00:00,1
12990,20815,宋仲基,2016-04-05 11:53:16,2016-04-09 00:00:00,1
13243,21234,宋仲基,2016-04-11 12:01:53,2016-04-11 00:00:00,1
13313,21335,宋仲基,2016-04-11 17:50:05,2016-04-11 00:00:00,1
13314,21336,宋仲基,2016-04-11 17:50:05,2016-04-12 00:00:00,1
13315,21337,宋仲基,2016-04-11 17:50:05,2016-04-13 00:00:00,1
13316,21338,宋仲基,2016-04-11 17:50:05,2016-04-14 00:00:00,1
13317,21339,宋仲基,2016-04-11 17:50:05,2016-04-15 00:00:00,1
13318,21340,宋仲基,2016-04-11 17:50:05,2016-04-16 00:00:00,1